### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by bdm634** [fishsticksnom/kp3s_3d_touch_guide#1]
I follow these steps exactly. 

After the Z probe wizard it shows at the bottom probe wizard failed and if I attempt the tramming... It jams the nozzle down into the bed and I need to shut up

Also is this for the new v1.3 kingroon board where you have to plug the 3d touch 2 pin into Z+ like in the updated video?

**Comment by fishsticksnom** [comment]
Hi there I just update the guide, it was incomplete. I add a section for how to connect the cables from the sensor into the motherboard as well I add some prusa slicer profiles at the bottom of the guide, I haven't use my printer in quite some time, If i remember correctly a had an error using the the prusa profiles in combination with octoprint to fix it I delete gcode settings in octoprint, please let me know if this fix your issue with the Z probe.
